name: NetworkTest

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  package:
   runs-on: ubuntu-latest
   
   steps:
     - name: Checkout
       uses: actions/checkout@v2
       
     - name: Package
       run: tar -czvf Block3.T08G06.tar.gz CMakeLists.txt src/
       
     - name: Upload Artifact 
       uses: actions/upload-artifact@v2
       with:
         name: project-source
         path: Block3.T08G06.tar.gz
         if-no-files-found: error
       
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v2
      with:
        name: build

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: build
        if-no-files-found: error
  
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: build
